name: quad_env
channels:
  - main
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.8
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.116
  - blas-devel=3.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - cloudpickle=2.2.0
  - colorama=0.4.5
  - contourpy=1.0.5
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=1.1.1
  - flake8=5.0.4
  - fonttools=4.37.4
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gym=0.21.0
  - imageio=2.22.4
  - importlib-metadata=4.11.4
  - ipython=8.5.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libprotobuf=3.21.7
  - libsqlite=3.39.4
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - llvmlite=0.39.1
  - matplotlib=3.6.1
  - matplotlib-base=3.6.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - ninja=1.11.0
  - nomkl=3.0=0
  - numba=0.56.3
  - numpy=1.19.5
  - openblas=0.3.21
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.1
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - plotly=5.10.0
  - progressbar2=4.1.1
  - prompt-toolkit=3.0.31
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.9.1
  - pycparser=2.21
  - pyflakes=2.5.0
  - pygments=2.13.0
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-utils=3.3.3
  - python_abi=3.9
  - pytorch=1.12.1
  - pytz=2022.5
  - readline=8.1.2
  - reportlab=3.5.68
  - scikit-learn=1.1.2
  - scipy=1.10
  - seaborn=0.10.1
  - setuptools=65.5.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.39.4
  - stack_data=0.5.1
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tenacity=8.1.0
  - threadpoolctl
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typing_extensions=4.4.0
  - tzdata=2022e
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.9.0
  - zstd=1.5.2
  - pip:
    - brainforge==0.1.0
    - gmr==1.6.2
    - ilqr==0.2.0
    - mycolorpy==1.5.1
    - theano==1.0.5
    - git+https://github.com/anassinator/ilqr
#prefix: /opt/homebrew/Caskroom/miniforge/base/envs/quad_env
